services:
  - type: web
    name: 404PathNotFound
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn backend.server:app
    envVars:
      - key: PORT
        value: 10000
